name: Batch Git Clone and Upload

on:
  workflow_dispatch:

jobs:
  batch_clone_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "pengguo2022@163.com"
        git config --global user.name "Polaris-P"

    - name: Clone repositories
      run: |
        REPO_URLS="https://git.openwrt.org/feed/packages.git https://git.openwrt.org/project/luci.git https://git.openwrt.org/feed/routing.git https://git.openwrt.org/feed/telephony.git"
        CLONE_DIR="/etc/openwrt"
        for repo_url in $REPO_URLS; do
          git clone $repo_url $CLONE_DI
        done

    - name: Upload cloned data
      run: |
        cd $CLONE_DIR
        git add .
        git commit -m "Batch clone data"
        git push origin main
